# Uncomment the next line to define a global platform for your project
# platform :ios, '14.1'

target 'Tempo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tempo

  # AR stuff
  pod 'ARCL'
  
  # HTTP requests
  pod 'Alamofire', '~> 5.5'

  # easier JSON handling
  pod 'SwiftyJSON', '~> 4.0'

end
